### PR TITLE
Try out using elm-live instead.

### PR DESCRIPTION
**Pull request by ootoovak**
@annavlz and @zerkms here is the [elm-live](https://www.npmjs.com/package/elm-live) implementation as requested.

### CODE REVIEW

**Comment by ootoovak** [comment]
If you prefer the Webpack implementation it is ok to me if you don't merge this in.

**Comment by zerkms** [comment]
@ootoovak merged + made a minor change at https://github.com/elm-wellington/math-trainer/commit/75bbca0b0b14030a20fe02040ba90a6f1a13c536

Thanks.

**Comment by ootoovak** [comment]
@zerkms isn't that going to require `elm-live` to be installed with `npm install -g elm-live` rather than just with `npm install`? I'm fine either way but might want to add it to the ReadMe if `elm-live` is needed to be installed globally.

**Comment by zerkms** [comment]
@ootoovak nope, `npm run` takes into account the `node_modules/.bin` directory that has a symlink to `elm-live` executable

**Comment by ootoovak** [comment]
:+1: Ah, cool. Just took my queues from [this package.json](https://github.com/philcockfield/ui-harness/blob/master/package.json#L14) but good to know re `node_modules/.bin`.

**Pull request merged**
